variables:
  S3_BUCKET_NAME: eks-dtap-shared

deploy:
  environment: production
  image: cellulantops/cicdtools:awsconsulskaffoldocker
  script:
    - aws s3 cp --region=eu-west-1 cicd-test.sh s3://eks-dtap-shared/cicdscripts/
