image: cellulantops/cicdtools:awsconsulskaffoldocker

stages:
  - build
  - test
  - deploy
  
before_script:
  - echo "Downloading packages"
  - sudo apt install nodejs
  - node –version
  - npm install
  - gem install
  - bundle install
  - echo "completed installing dependencies"



build:
  stage: build
  script:
    - npm run dist
    - npm test
    - npm run docs

test:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"



deploy:
  stage: deploy
  script:
    - aws s3 cp --region=eu-west-1 cicd-bootstrap.sh s3://$S3_BUCKET_NAME/cicdscripts/
    - aws s3api put-object-acl --bucket eks-dtap-shared --key cicdscripts/cicd-bootstrap.sh --acl public-read 1> /dev/null 2>&1
  only:
    changes:
      - cicd-bootstrap.sh

  tags:
    - job-pipeline
