---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name: "{{ .Chart.Name }}-{{ .Release.Namespace }}"
spec:
  prefix: {{ .Values.ambassador.prefix }}
  service: "{{ .Chart.Name }}.{{ .Release.Namespace }}:{{ .Values.service.port }}"
  host: "{{ .Values.ambassador.hostname }}"
  timeout_ms: {{ .Values.ambassador.timeoutMs }} 
  connect_timeout_ms: {{ .Values.ambassador.connectTimeoutms }}
  idle_timeout_ms: {{ .Values.ambassador.idleTimeoutms }}