{{- if .Values.kedaprometheus.enabled -}}
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-scaledobject-{{ include "demo.fullname" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    deploymentName: {{ include "demo.fullname" . }}
  pollingInterval: {{ .Values.kedaprometheus.pollingInterval }}
  cooldownPeriod:  {{ .Values.kedaprometheus.cooldownPeriod }}
  minReplicaCount: {{ .Values.kedaprometheus.minReplicaCount }}
  maxReplicaCount: {{.Values.kedaprometheus.maxReplicaCount }}
  triggers:
  - type: prometheus
    metadata:
      serverAddress: {{ .Values.kedaprometheus.serverAddress }}
      metricName: {{ .Values.kedaprometheus.metricName }}
      threshold: "{{ .Values.kedaprometheus.threshold }}"
      query: {{ .Values.kedaprometheus.query }}
{{- end }}