apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
  # annotations:
  #   {{- if .Values.ambassador.enabled -}}
  #   getambassador.io/config: |
  #     ---
  #     apiVersion: ambassador/v1
  #     kind:  Mapping
  #     name: "{{ .Chart.Name }}-{{ .Release.Namespace }}"
  #     prefix: {{ .Values.ambassador.prefix }}
  #     service: "{{ .Chart.Name }}.{{ .Release.Namespace }}:{{ .Values.service.port }}"
  #     host: "{{ .Values.ambassador.hostname }}"
  #     timeout_ms: {{ .Values.ambassador.timeoutMs }} 
  #     connect_timeout_ms: {{ .Values.ambassador.connectTimeoutms }}
  #     idle_timeout_ms: {{ .Values.ambassador.idleTimeoutms }}
  #   {{- end }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "demo.selectorLabels" . | nindent 4 }}
